### ISSUE TITLE
Substituir http://plataforma.saude.gov.br/novocoronavirus por https://covid.saude.gov.br/

### ISSUE THREAD

**Issue by fititnt** [EticaAI/coronavirus-cplp#5]
O http://plataforma.saude.gov.br/novocoronavirus está completamente offline faz dias. O https://covid.saude.gov.br/ ao que tudo indica agora o subistitui oficialmente.

Eu estou na correria aqui, mas se alguém quiser fazer um commit trocando eles, pode fazer no meu lugar.

**Comment by jailsonnt** [comment]
alteração realizada no Readme.md
